name: Docker Image CI Extraction

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# allow to run workflow manually
  workflow_dispatch:
  
jobs:

  build:

    runs-on: centos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: docker
      run: docker build . -t sci-extraction:latest
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: user/app:latest
