name: Docker Image CI Extraction

on:
  push:
    branches: [ "pdf-content-extraction" ]
  pull_request:
    branches: [ "pdf-content-extraction" ]

## allow to run workflow manually
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
#     - name: Build the Docker image
      
#       run: docker build . -t sci-provenance:latest
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
#       working-directory: docker
      with:
        context: docker
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sci-extraction:latest

