name: Docker Image copy-move

on:
  push:
    branches: [ "copy-move-detection" ]
  pull_request:
    branches: [ "copy-move-detection" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t sci-cmfd:latest
